### PR TITLE
fix: do not pick a buildpack if a jenkins-x.yml file already exists

### LINKED ISSUE #76: importing a project that already contains a `jenkins-x.yml` should not re-apply a build pack
as its already got a pipeline setup

### PR DESCRIPTION
**Pull request by hervelemeur**
Fixes #76

### CODE REVIEW

**Comment by jstrachan** [comment]
@hervelemeur thanks for this! I've merged this PR into this commit: https://github.com/jenkins-x/jx-project/pull/87/commits/51dec44fda62eceb64a8a64811d150069efed9d5

and fixed up the unit tests. So gonna close this one - thanks though!

**Comment by hervelemeur** [comment]
No problem, just seen your commit :)

**Pull request closed without merging**
