### PR TITLE
feat: updated existing repository check logic to support more vendors

### PR DESCRIPTION
**Pull request by ryneal**
change the check to use 404 response status rather than the type of error returned from the jx-helpers utils

### CODE REVIEW

**Comment by jstrachan** [comment]
error:
```

WARNING: organisation orga detected from URL https://github.com/orga/myrepo. '--org orgb' will be ignored
--
  | --- FAIL: TestShouldReturnErrorWhenErrorReturnedAndResponseIsSuccessful (0.00s)
  | panic: interface conversion: interface {} is **scm.Repository, not *scm.Repository [recovered]
  | panic: interface conversion: interface {} is **scm.Repository, not *scm.Repository
  |  
  | goroutine 418 [running]:
  | testing.tRunner.func1.1(0x1960e80, 0xc0007f7aa0)
  | /usr/local/go/src/testing/testing.go:1072 +0x30d
  | testing.tRunner.func1(0xc0012f2c00)
  | /usr/local/go/src/testing/testing.go:1075 +0x41a
  | panic(0x1960e80, 0xc0007f7aa0)
  | /usr/local/go/src/runtime/panic.go:969 +0x1b9
  | github.com/jenkins-x/jx-project/pkg/cmd/importcmd_test.(*MockRepositoryService).Find(0xc0002ff320, 0x1de7ba0, 0xc00012c010, 0xc001a35210, 0x9, 0x1b82ea0, 0x4, 0xc001a35210, 0x9)
  | /workspace/source/pkg/cmd/importcmd/input_test.go:20 +0x219
  | github.com/jenkins-x/jx-project/pkg/cmd/importcmd.(*ImportOptions).ValidateRepositoryName(0xc00120bc38, 0x1b82de8, 0x4, 0x1b82ea0, 0x4, 0x2, 0xc001240320)
  | /workspace/source/pkg/cmd/importcmd/input.go:242 +0xd5
  | github.com/jenkins-x/jx-project/pkg/cmd/importcmd_test.TestShouldReturnErrorWhenErrorReturnedAndResponseIsSuccessful(0xc0012f2c00)
  | /workspace/source/pkg/cmd/importcmd/input_test.go:61 +0x339
  | testing.tRunner(0xc0012f2c00, 0x1c62be0)
  | /usr/local/go/src/testing/testing.go:1123 +0xef
  | created by testing.(*T).Run
  | /usr/local/go/src/testing/testing.go:1168 +0x2b3
  | FAIL	github.com/jenkins-x/jx-project/pkg/cmd/importcmd	76.209s
  | ?   	github.com/jenkins-x/jx-project/pkg/cmd/importcmd/test_data/import_projects/golang	[no test files]
  | about to run: git clone https://github.com/jx3-gitops-repositories/jx3-gke-gsm /tmp/jx-git-127794829 in dir /tmp
  | Cloning into '/tmp/jx-git-127794829'...
  | --- FAIL: TestCreateQuickstartProjects (2.72s)
  | quickstart_integration_test.go:35:
  | Error Trace:	quickstart_integration_test.go:35
  | Error:      	Received unexpected error:
  | Not Found
  | failed to check if repository dummy/mynode exists
  | github.com/jenkins-x/jx-project/pkg/cmd/importcmd.(*ImportOptions).ValidateRepositoryName
  | /workspace/source/pkg/cmd/importcmd/input.go:249
  | github.com/jenkins-x/jx-project/pkg/cmd/importcmd.(*ImportOptions).PickNewOrExistingGitRepository
  | /workspace/source/pkg/cmd/importcmd/input.go:219
  | github.com/jenkins-x/jx-project/pkg/cmd/importcmd.(*ImportOptions).GetGitRepositoryDetails
  | /workspace/source/pkg/cmd/importcmd/import.go:1279
  | github.com/jenkins-x/jx-project/pkg/cmd/root.(*CreateQuickstartOptions).CreateQuickStart
  | /workspace/source/pkg/cmd/root/quickstart.go:151
  | github.com/jenkins-x/jx-project/pkg/cmd/root.(*CreateQuickstartOptions).Run
  | /workspace/source/pkg/cmd/root/quickstart.go:136
  | github.com/jenkins-x/jx-project/pkg/cmd/root_test.TestCreateQuickstartProjects
  | /workspace/source/pkg/cmd/root/quickstart_integration_test.go:34
  | testing.tRunner
  | /usr/local/go/src/testing/testing.go:1123
  | runtime.goexit
  | /usr/local/go/src/runtime/asm_amd64.s:1374
  | Test:       	TestCreateQuickstartProjects

```

**Comment by ryneal** [comment]
@jstrachan to resolve one of the test failures I will need to merge my PR on go-scm https://github.com/jenkins-x/go-scm/pull/220

**Pull request merged**
